language: go

sudo: required

go:
- 1.11.x
- 1.12.x

env:
  global:
    - PATH=/snap/bin:$PATH
    - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

after_success:
  - go test -v --cover ./...

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true